{
 "title": "Boursorama",
 "time": { "from": "2021-03-11T23:00:00.000Z", "to": "2021-03-18T00:00:00.000Z" },
 "panels": [
  {
   "title": "Variation des indices (en %)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Indice AS metric,\n  Variation\nFROM cours\nWHERE\n  $__timeFilter(Date)\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Ouvertures le 18 mars 2021",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Indice AS metric,\n  Ouverture\nFROM cours\nWHERE\n  $__timeFilter(Date) AND\n  Date = '2021-03-18'\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Haut & Bas du CAC 40",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Indice AS metric,\n  Bas,\n  Haut\nFROM cours\nWHERE\n  $__timeFilter(Date) AND\n  Indice = 'CAC 40 '\nORDER BY Date"
    }
   ]
  },
  {
   "title": "Evolution du volume des transactions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Date AS \"time\",\n  Indice AS metric,\n  Volume\n  \nFROM cours\nWHERE\n  $__timeFilter(Date) AND\n  Indice = 'CAC 40 ' OR Indice = 'IBEX 35'\nORDER BY Date"
    }
   ]
  }
 ]
}